services:

  proxy:
    image: nginx:stable-alpine
    ports: [3000:3000]
    volumes: [./proxy/nginx.conf:/etc/nginx/nginx.conf:ro]
    depends_on: [frontend, backend]

  frontend:
    build:
      context: ./frontend
      target: dev
    tty: true
    ports: [3001:3001]
    volumes: [./frontend:/frontend]
    depends_on: [backend]

  backend:
    build:
      context: ./backend
      target: dev
    ports: [3002:3002]
    volumes: [./backend:/backend]
    env_file: [./backend/.env]
    environment:
      - ENV=local
      - PORT=3002
      - DB_HOST=db
      - DB_USER=local
      - DB_PASS=local
      - DB_NAME=local
    depends_on: [db]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local

  infra:
    image: hashicorp/terraform:1.9
    working_dir: /infra
    volumes: [./infra:/infra, ~/.aws:/root/.aws]
    entrypoint: sh
    tty: true